erDiagram
    %% Parameters:
%%   Focus: journal
%%   Domains: pathway
%%   Chart Type: ER
    "pathway_dmImage" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_dmNavigation" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_dmNews" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_activity" {
        🔥 CORE UUID ObjectID
    }

    "pathway_activityDef" {
        🔥 CORE UUID ObjectID
    }

    "pathway_journal" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_journalDef" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_media" {
        🔥 CORE UUID ObjectID
    }

    "pathway_memberType" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_progMember" {
        🔥 CORE UUID ObjectID
    }

    "pathway_programme" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_trackerDef" {
        💧 UTILITIES UUID ObjectID
    }

    "farcrycms_dmEmail" {
        📞 SERVICES UUID ObjectID
    }

    "farcrycms_dmFacts" {
        💧 UTILITIES UUID ObjectID
    }

    "farcrycms_farFeedback" {
        📞 SERVICES UUID ObjectID
    }

    "zfarcrycore_dmFile" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmHTML" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmInclude" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmProfile" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farBarnacle" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farGroup" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farPermission" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farRole" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farUser" {
        🛡️ AUTH UUID ObjectID
    }

    %% Direct FK Relationships
    "pathway_dmNavigation" ||--|| "pathway_dmImage" : sourceImageID
    "pathway_activity" ||--|| "pathway_progMember" : progMemberID
    "pathway_activity" ||--|| "pathway_activityDef" : activityDefID
    "pathway_activityDef" ||--|| "pathway_programme" : programmeID
    "pathway_activityDef" ||--|| "pathway_dmImage" : teaserImage
    "pathway_activityDef" ||--|| "pathway_media" : defaultMediaID
    "pathway_activityDef" ||--|| "pathway_journalDef" : journalID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker03ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker04ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker05ID
    "pathway_journal" ||--|| "pathway_progMember" : progMemberID
    "pathway_journal" ||--|| "pathway_journalDef" : journalDefID
    "pathway_journal" ||--|| "pathway_activity" : activityID
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_journalDef" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_programme" : programmeID
    "pathway_progMember" ||--|| "pathway_programme" : programmeID
    "pathway_progMember" ||--|| "pathway_activity" : currActivityID
    "pathway_programme" ||--|| "pathway_dmImage" : Logo
    "pathway_programme" ||--|| "pathway_activityDef" : firstActivityDefID
    "pathway_programme" ||--|| "pathway_activityDef" : lastActivityDefID
    "pathway_trackerDef" ||--|| "pathway_programme" : programmeID
    "farcrycms_dmFacts" ||--|| "pathway_dmImage" : imageID
    "pathway_dmNews" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_dmFile" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_dmHTML" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_dmInclude" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_farBarnacle" ||--|| "zfarcrycore_farRole" : roleid
    "zfarcrycore_farBarnacle" ||--|| "zfarcrycore_farPermission" : permissionid
    %% End Direct FK Relationships

    %% Special Joins
    "zfarcrycore_farUser" ||--|| "zfarcrycore_dmProfile" : userID_to_userName_userDirectory
    %% End Special Joins

    %% Self-Referencing Relationships for farPermission
    %% Self-refs include: aRelatedtypes
    "zfarcrycore_farPermission" ||--|| "zfarcrycore_farPermission" : self_refs
    %% End Self-Referencing Relationships for farPermission

    %% Self-Referencing Relationships for activityDef
    %% Self-refs include: onEndID, aCuePointActivities, aInteract1Activities, aInteract2Activities, aInteract3Activities, aInteract4Activities, aInteract5Activities
    "pathway_activityDef" ||--|| "pathway_activityDef" : self_refs
    %% End Self-Referencing Relationships for activityDef

    %% Join Table Relationships
    "pathway_activityDef" }o--|| "pathway_media" : aMediaIDs
    "pathway_programme" }o--|| "pathway_activityDef" : aFollowupActivityDefIDs
    "pathway_programme" }o--|| "pathway_trackerDef" : aTrackerIDs
    "pathway_programme" }o--|| "zfarcrycore_dmFile" : aObjectIDs
    "zfarcrycore_dmProfile" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farPermission" : aPermissions
    "zfarcrycore_farUser" }o--|| "zfarcrycore_farGroup" : aGroups
    %% End Join Table Relationships


    %% Entity Styling
    style pathway_dmImage fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_dmNavigation fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_dmNews fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_activity fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_activityDef fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_journal fill:#d75500,stroke:#f57c00,stroke-width:4px,color:#fff
    style pathway_journalDef fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_media fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_memberType fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_progMember fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_programme fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style pathway_trackerDef fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style farcrycms_dmEmail fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style farcrycms_dmFacts fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style farcrycms_farFeedback fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_dmFile fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_dmHTML fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_dmInclude fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_dmProfile fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_farBarnacle fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_farGroup fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_farPermission fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_farRole fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff
    style zfarcrycore_farUser fill:#1a1a1a,stroke:#0d0d0d,stroke-width:1px,color:#fff

