erDiagram
    %% Parameters:
%%   Focus: activityDef
%%   Domains: programme
%%   Chart Type: ER
    "pathway_dmImage" {
        UUID ObjectID
    }

    "pathway_activity" {
        UUID ObjectID
    }

    "pathway_activityDef" {
        UUID ObjectID
    }

    "pathway_guide" {
        UUID ObjectID
    }

    "pathway_journalDef" {
        UUID ObjectID
    }

    "pathway_media" {
        UUID ObjectID
    }

    "pathway_programme" {
        UUID ObjectID
    }

    "pathway_progRole" {
        UUID ObjectID
    }

    "pathway_testimonial" {
        UUID ObjectID
    }

    "pathway_trackerDef" {
        UUID ObjectID
    }

    %% Direct FK Relationships
    "pathway_activity" ||--|| "pathway_activityDef" : activityDefID
    "pathway_activityDef" ||--|| "pathway_programme" : programmeID
    "pathway_activityDef" ||--|| "pathway_dmImage" : teaserImage
    "pathway_activityDef" ||--|| "pathway_guide" : guideID
    "pathway_activityDef" ||--|| "pathway_progRole" : role
    "pathway_activityDef" ||--|| "pathway_media" : defaultMediaID
    "pathway_activityDef" ||--|| "pathway_journalDef" : journalID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker03ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker04ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker05ID
    "pathway_guide" ||--|| "pathway_dmImage" : picture
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_journalDef" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_guide" : guideID
    "pathway_media" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_progRole" : roleID
    "pathway_programme" ||--|| "pathway_dmImage" : Logo
    "pathway_programme" ||--|| "pathway_activityDef" : firstActivityDefID
    "pathway_programme" ||--|| "pathway_activityDef" : lastActivityDefID
    "pathway_progRole" ||--|| "pathway_programme" : programmeID
    "pathway_testimonial" ||--|| "pathway_activityDef" : activityDefID
    "pathway_trackerDef" ||--|| "pathway_programme" : programmeID
    %% End Direct FK Relationships

    %% Special Joins
    %% End Special Joins

    %% Self-Referencing Relationships for activityDef
    %% Self-refs include: onEndID, aCuePointActivities, aInteract1Activities, aInteract2Activities, aInteract3Activities, aInteract4Activities, aInteract5Activities
    "pathway_activityDef" ||--|| "pathway_activityDef" : self_refs
    %% End Self-Referencing Relationships for activityDef

    %% Join Table Relationships
    "pathway_activityDef" }o--|| "pathway_media" : aMediaIDs
    "pathway_programme" }o--|| "pathway_activityDef" : aFollowupActivityDefIDs
    "pathway_programme" }o--|| "pathway_trackerDef" : aTrackerIDs
    %% End Join Table Relationships


    %% Entity Styling
    style pathway_dmImage fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_activity fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_activityDef fill:#d75500,stroke:#f57c00,stroke-width:4px,color:#fff
    style pathway_guide fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_journalDef fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_media fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_programme fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_progRole fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_testimonial fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_trackerDef fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff

