classDiagram
    %% Parameters:
%%   Focus: dmImage
%%   Domains: site
%%   Chart Type: Class
    class pathway_dmImage {
        +UUID ObjectID
        +string name
    }

    class pathway_dmNavigation {
        +UUID ObjectID
        +string name
    }

    class pathway_dmNews {
        +UUID ObjectID
        +string name
    }

    class pathway_activityDef {
        +UUID ObjectID
        +string name
    }

    class pathway_center {
        +UUID ObjectID
        +string name
    }

    class pathway_guide {
        +UUID ObjectID
        +string name
    }

    class pathway_memberGroup {
        +UUID ObjectID
        +string name
    }

    class pathway_partner {
        +UUID ObjectID
        +string name
    }

    class pathway_programme {
        +UUID ObjectID
        +string name
    }

    class pathway_referer {
        +UUID ObjectID
        +string name
    }

    class farcrycms_dmCarouselItem {
        +UUID ObjectID
        +string name
    }

    class farcrycms_dmEvent {
        +UUID ObjectID
        +string name
    }

    class farcrycms_dmFacts {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmFile {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmHTML {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmInclude {
        +UUID ObjectID
        +string name
    }

    pathway_dmNavigation --> pathway_dmImage : sourceImageID
    pathway_activityDef --> pathway_programme : programmeID
    pathway_activityDef --> pathway_dmImage : teaserImage
    pathway_activityDef --> pathway_guide : guideID
    pathway_center --> pathway_dmImage : Logo
    pathway_center --> pathway_partner : partnerID
    pathway_center --> pathway_memberGroup : memberGroupID
    pathway_guide --> pathway_dmImage : picture
    pathway_guide --> pathway_partner : partnerID
    pathway_guide --> pathway_center : centerID
    pathway_memberGroup --> pathway_partner : partnerID
    pathway_memberGroup --> pathway_dmImage : Logo
    pathway_memberGroup --> zfarcrycore_dmFile : resourcePosterID
    pathway_memberGroup --> zfarcrycore_dmFile : resourceHandoutID
    pathway_memberGroup --> zfarcrycore_dmHTML : supportPage
    pathway_memberGroup --> pathway_dmNavigation : selfRegNavID
    pathway_memberGroup --> zfarcrycore_dmFile : selfRegQrFileID
    pathway_partner --> pathway_dmImage : Logo
    pathway_programme --> pathway_partner : partnerID
    pathway_programme --> pathway_dmImage : Logo
    pathway_programme --> pathway_activityDef : firstActivityDefID
    pathway_programme --> pathway_activityDef : lastActivityDefID
    pathway_referer --> pathway_dmImage : picture
    pathway_referer --> pathway_partner : partnerID
    pathway_referer --> pathway_memberGroup : memberGroupID
    pathway_referer --> pathway_center : centerID
    farcrycms_dmCarouselItem --> pathway_dmImage : imgSourceID
    farcrycms_dmEvent --> pathway_dmImage : teaserImage
    farcrycms_dmFacts --> pathway_dmImage : imageID
    pathway_dmNews --> pathway_dmImage : teaserImage
    zfarcrycore_dmFile --> pathway_dmImage : teaserImage
    zfarcrycore_dmHTML --> pathway_dmImage : teaserImage
    zfarcrycore_dmInclude --> pathway_dmImage : teaserImage
    pathway_center --> pathway_referer : aReferers
    pathway_partner --> pathway_center : aCenters
    pathway_partner --> pathway_referer : aReferers
    pathway_programme --> pathway_activityDef : aFollowupActivityDefIDs
    pathway_programme --> zfarcrycore_dmFile : aObjectIDs
    pathway_activityDef --> pathway_activityDef : onEndID, aCuePointActivities, aInteract1Activities, aInteract2Activities, aInteract3Activities, aInteract4Activities, aInteract5Activities
    pathway_dmNavigation --> pathway_dmNavigation : internalRedirectID, ExternalLink

    %% Special Joins
    %% End Special Joins


    %% Entity Styling
    style pathway_dmImage fill:#d75500,stroke:#f57c00,stroke-width:4px,color:#fff
    style pathway_dmNavigation fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_dmNews fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style pathway_activityDef fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_center fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_guide fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_memberGroup fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_partner fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_programme fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style pathway_referer fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style farcrycms_dmCarouselItem fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style farcrycms_dmEvent fill:#1963d2,stroke:#1565c0,stroke-width:4px,color:#fff
    style farcrycms_dmFacts fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style zfarcrycore_dmFile fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style zfarcrycore_dmHTML fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff
    style zfarcrycore_dmInclude fill:#693a00,stroke:#5d2e00,stroke-width:4px,color:#fff

