classDiagram
    %% Parameters:
%%   Focus: media
%%   Domains: pathway
%%   Chart Type: Class
    class pathway_dmImage {
        +UUID ObjectID
        +string name
    }

    class pathway_dmNavigation {
        +UUID ObjectID
        +string name
    }

    class pathway_dmNews {
        +UUID ObjectID
        +string name
    }

    class pathway_activityDef {
        +UUID ObjectID
        +string name
    }

    class pathway_journalDef {
        +UUID ObjectID
        +string name
    }

    class pathway_library {
        +UUID ObjectID
        +string name
    }

    class pathway_media {
        +UUID ObjectID
        +string name
    }

    class pathway_memberType {
        +UUID ObjectID
        +string name
    }

    class pathway_partner {
        +UUID ObjectID
        +string name
    }

    class pathway_programme {
        +UUID ObjectID
        +string name
    }

    class pathway_progRole {
        +UUID ObjectID
        +string name
    }

    class pathway_trackerDef {
        +UUID ObjectID
        +string name
    }

    class farcrycms_dmEmail {
        +UUID ObjectID
        +string name
    }

    class farcrycms_dmFacts {
        +UUID ObjectID
        +string name
    }

    class farcrycms_farFeedback {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmFile {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmHTML {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmInclude {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_dmProfile {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_farBarnacle {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_farGroup {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_farPermission {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_farRole {
        +UUID ObjectID
        +string name
    }

    class zfarcrycore_farUser {
        +UUID ObjectID
        +string name
    }

    pathway_dmNavigation --> pathway_dmImage : sourceImageID
    pathway_activityDef --> pathway_programme : programmeID
    pathway_activityDef --> pathway_dmImage : teaserImage
    pathway_activityDef --> pathway_progRole : role
    pathway_activityDef --> pathway_media : defaultMediaID
    pathway_activityDef --> pathway_journalDef : journalID
    pathway_activityDef --> pathway_trackerDef : tracker01ID
    pathway_activityDef --> pathway_trackerDef : tracker02ID
    pathway_activityDef --> pathway_trackerDef : tracker03ID
    pathway_activityDef --> pathway_trackerDef : tracker04ID
    pathway_activityDef --> pathway_trackerDef : tracker05ID
    pathway_journalDef --> pathway_trackerDef : tracker01ID
    pathway_journalDef --> pathway_trackerDef : tracker02ID
    pathway_journalDef --> pathway_programme : programmeID
    pathway_library --> pathway_media : mediaID
    pathway_media --> pathway_partner : partnerID
    pathway_media --> pathway_programme : programmeID
    pathway_media --> pathway_progRole : roleID
    pathway_partner --> pathway_dmImage : Logo
    pathway_partner --> zfarcrycore_dmProfile : dmProfileID
    pathway_partner --> zfarcrycore_dmProfile : seniorSupportID
    pathway_programme --> pathway_partner : partnerID
    pathway_programme --> pathway_dmImage : Logo
    pathway_programme --> pathway_activityDef : firstActivityDefID
    pathway_programme --> pathway_activityDef : lastActivityDefID
    pathway_progRole --> pathway_programme : programmeID
    pathway_trackerDef --> pathway_programme : programmeID
    farcrycms_dmFacts --> pathway_dmImage : imageID
    pathway_dmNews --> pathway_dmImage : teaserImage
    zfarcrycore_dmFile --> pathway_dmImage : teaserImage
    zfarcrycore_dmHTML --> pathway_dmImage : teaserImage
    zfarcrycore_dmInclude --> pathway_dmImage : teaserImage
    zfarcrycore_farBarnacle --> zfarcrycore_farRole : roleid
    zfarcrycore_farBarnacle --> zfarcrycore_farPermission : permissionid
    pathway_activityDef --> pathway_media : aMediaIDs
    pathway_programme --> pathway_activityDef : aFollowupActivityDefIDs
    pathway_programme --> pathway_trackerDef : aTrackerIDs
    pathway_programme --> zfarcrycore_dmFile : aObjectIDs
    zfarcrycore_dmProfile --> zfarcrycore_farGroup : aGroups
    zfarcrycore_farRole --> zfarcrycore_farGroup : aGroups
    zfarcrycore_farRole --> zfarcrycore_farPermission : aPermissions
    zfarcrycore_farUser --> zfarcrycore_farGroup : aGroups
    pathway_activityDef --> pathway_activityDef : onEndID, aCuePointActivities, aInteract1Activities, aInteract2Activities, aInteract3Activities, aInteract4Activities, aInteract5Activities
    zfarcrycore_farPermission --> zfarcrycore_farPermission : aRelatedtypes
    pathway_dmNavigation --> pathway_dmNavigation : internalRedirectID, ExternalLink

    %% Special Joins
    zfarcrycore_farUser --> zfarcrycore_dmProfile : userID_to_userName_userDirectory
    %% End Special Joins


    %% Entity Styling
    style pathway_dmImage fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_dmNavigation fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_dmNews fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_activityDef fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    style pathway_journalDef fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_library fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    style pathway_media fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_memberType fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style pathway_partner fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    style pathway_programme fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    style pathway_progRole fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    style pathway_trackerDef fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style farcrycms_dmEmail fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style farcrycms_dmFacts fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style farcrycms_farFeedback fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_dmFile fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_dmHTML fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_dmInclude fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_dmProfile fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_farBarnacle fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_farGroup fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_farPermission fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_farRole fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff
    style zfarcrycore_farUser fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff

