erDiagram
    %% Parameters:
%%   Focus: activityDef
%%   Domains: pathway
%%   Chart Type: ER
    "pathway_dmImage" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_dmNavigation" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_dmNews" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_activity" {
        🔥 CORE UUID ObjectID
    }

    "pathway_activityDef" {
        🔥 CORE UUID ObjectID
    }

    "pathway_journalDef" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_media" {
        🔥 CORE UUID ObjectID
    }

    "pathway_member" {
        🔥 CORE UUID ObjectID
    }

    "pathway_memberType" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_programme" {
        💧 UTILITIES UUID ObjectID
    }

    "pathway_progRole" {
        📞 SERVICES UUID ObjectID
    }

    "pathway_testimonial" {
        📞 SERVICES UUID ObjectID
    }

    "pathway_trackerDef" {
        💧 UTILITIES UUID ObjectID
    }

    "farcrycms_dmEmail" {
        📞 SERVICES UUID ObjectID
    }

    "farcrycms_dmFacts" {
        💧 UTILITIES UUID ObjectID
    }

    "farcrycms_farFeedback" {
        📞 SERVICES UUID ObjectID
    }

    "zfarcrycore_dmFile" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmHTML" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmInclude" {
        💧 UTILITIES UUID ObjectID
    }

    "zfarcrycore_dmProfile" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farBarnacle" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farGroup" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farPermission" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farRole" {
        🛡️ AUTH UUID ObjectID
    }

    "zfarcrycore_farUser" {
        🛡️ AUTH UUID ObjectID
    }

    %% Direct FK Relationships
    "pathway_dmNavigation" ||--|| "pathway_dmImage" : sourceImageID
    "pathway_activity" ||--|| "pathway_activityDef" : activityDefID
    "pathway_activityDef" ||--|| "pathway_programme" : programmeID
    "pathway_activityDef" ||--|| "pathway_dmImage" : teaserImage
    "pathway_activityDef" ||--|| "pathway_progRole" : role
    "pathway_activityDef" ||--|| "pathway_media" : defaultMediaID
    "pathway_activityDef" ||--|| "pathway_journalDef" : journalID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker03ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker04ID
    "pathway_activityDef" ||--|| "pathway_trackerDef" : tracker05ID
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker01ID
    "pathway_journalDef" ||--|| "pathway_trackerDef" : tracker02ID
    "pathway_journalDef" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_progRole" : roleID
    "pathway_member" ||--|| "pathway_memberType" : memberTypeID
    "pathway_member" ||--|| "pathway_activityDef" : activityDefID
    "pathway_member" ||--|| "pathway_progRole" : roleID
    "pathway_programme" ||--|| "pathway_dmImage" : Logo
    "pathway_programme" ||--|| "pathway_activityDef" : firstActivityDefID
    "pathway_programme" ||--|| "pathway_activityDef" : lastActivityDefID
    "pathway_progRole" ||--|| "pathway_programme" : programmeID
    "pathway_testimonial" ||--|| "pathway_member" : memberID
    "pathway_testimonial" ||--|| "pathway_activityDef" : activityDefID
    "pathway_trackerDef" ||--|| "pathway_programme" : programmeID
    "farcrycms_dmFacts" ||--|| "pathway_dmImage" : imageID
    "pathway_dmNews" ||--|| "pathway_dmImage" : teaserImage
    "farcrycms_farFeedback" ||--|| "pathway_member" : memberID
    "zfarcrycore_dmFile" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_dmHTML" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_dmInclude" ||--|| "pathway_dmImage" : teaserImage
    "zfarcrycore_farBarnacle" ||--|| "zfarcrycore_farRole" : roleid
    "zfarcrycore_farBarnacle" ||--|| "zfarcrycore_farPermission" : permissionid
    %% End Direct FK Relationships

    %% Special Joins
    "zfarcrycore_farUser" ||--|| "zfarcrycore_dmProfile" : userID_to_userName_userDirectory
    %% End Special Joins

    %% Self-Referencing Relationships for activityDef
    %% Self-refs include: onEndID, aCuePointActivities, aInteract1Activities, aInteract2Activities, aInteract3Activities, aInteract4Activities, aInteract5Activities
    "pathway_activityDef" ||--|| "pathway_activityDef" : self_refs
    %% End Self-Referencing Relationships for activityDef

    %% Self-Referencing Relationships for farPermission
    %% Self-refs include: aRelatedtypes
    "zfarcrycore_farPermission" ||--|| "zfarcrycore_farPermission" : self_refs
    %% End Self-Referencing Relationships for farPermission

    %% Join Table Relationships
    "pathway_activityDef" }o--|| "pathway_media" : aMediaIDs
    "pathway_member" }o--|| "zfarcrycore_farGroup" : aGroups
    "pathway_programme" }o--|| "pathway_activityDef" : aFollowupActivityDefIDs
    "pathway_programme" }o--|| "pathway_trackerDef" : aTrackerIDs
    "pathway_programme" }o--|| "zfarcrycore_dmFile" : aObjectIDs
    "zfarcrycore_dmProfile" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farPermission" : aPermissions
    "zfarcrycore_farUser" }o--|| "zfarcrycore_farGroup" : aGroups
    %% End Join Table Relationships


    %% Entity Styling
    %% domain_related tier
    style pathway_dmImage fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
    %% domain_other tier
    style pathway_dmNavigation fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style pathway_dmNews fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% related tier
    style pathway_activity fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    %% focus tier
    style pathway_activityDef fill:#d76400,stroke:#b34d00,stroke-width:2px,color:#fff
    %% domain_related tier
    style pathway_journalDef fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
    %% domain_related tier
    style pathway_media fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
    %% related tier
    style pathway_member fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    %% domain_other tier
    style pathway_memberType fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_related tier
    style pathway_programme fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
    %% related tier
    style pathway_progRole fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    %% related tier
    style pathway_testimonial fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
    %% domain_related tier
    style pathway_trackerDef fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
    %% domain_other tier
    style farcrycms_dmEmail fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style farcrycms_dmFacts fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style farcrycms_farFeedback fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_dmFile fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_dmHTML fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_dmInclude fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_dmProfile fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_farBarnacle fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_farGroup fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_farPermission fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_farRole fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% domain_other tier
    style zfarcrycore_farUser fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
    %% special join entity

