style focus fill:#d76400,stroke:#b34d00,stroke-width:2px,color:#fff
style domain_related fill:#9d3100,stroke:#7a2600,stroke-width:2px,color:#fff
style related fill:#883583,stroke:#6a2a6a,stroke-width:2px,color:#fff
style domain_other fill:#7e4f2b,stroke:#5d3d1f,stroke-width:2px,color:#eceff1
style other fill:#1a1a1a,stroke:#0d0d0d,stroke-width:2px,color:#fff




style error fill:#ff0000,stroke:#cc0000,stroke-width:3px,color:#fff
style special_join fill:#2196f3,stroke:#1976d2,stroke-width:2px,color:#fff