erDiagram
    activityDef {
        string id
        string name
    }
    activity {
        string id
        string name
    }
    aCuePointActivities {
        string id
        string name
    }
    aInteract1Activities {
        string id
        string name
    }
    aInteract2Activities {
        string id
        string name
    }
    aInteract3Activities {
        string id
        string name
    }
    aInteract4Activities {
        string id
        string name
    }
    aInteract5Activities {
        string id
        string name
    }
    aMediaIDs {
        string id
        string name
    }
    defaultMediaID {
        string id
        string name
    }
    guide {
        string id
        string name
    }
    journal {
        string id
        string name
    }
    media {
        string id
        string name
    }
    member {
        string id
        string name
    }
    memberGroup {
        string id
        string name
    }
    onEndID {
        string id
        string name
    }
    progMember {
        string id
        string name
    }
    programme {
        string id
        string name
    }
    progRole {
        string id
        string name
    }
    tracker {
        string id
        string name
    }
    tracker01 {
        string id
        string name
    }
    tracker02 {
        string id
        string name
    }
    tracker03 {
        string id
        string name
    }
    tracker04 {
        string id
        string name
    }
    tracker05 {
        string id
        string name
    }

    %% Relationships
    activityDef ||--o{ activity : "related to"
    activityDef ||--o{ aCuePointActivities : "related to"
    activityDef ||--o{ aInteract1Activities : "related to"
    activityDef ||--o{ aInteract2Activities : "related to"
    activityDef ||--o{ aInteract3Activities : "related to"
    activityDef ||--o{ aInteract4Activities : "related to"
    activityDef ||--o{ aInteract5Activities : "related to"
    activityDef ||--o{ aMediaIDs : "related to"
    activityDef ||--o{ defaultMediaID : "related to"
    activityDef ||--o{ guide : "related to"
    activityDef ||--o{ journal : "related to"
    activityDef ||--o{ media : "related to"
    activityDef ||--o{ member : "related to"
    activityDef ||--o{ memberGroup : "related to"
    activityDef ||--o{ onEndID : "related to"
    activityDef ||--o{ progMember : "related to"
    activityDef ||--o{ programme : "related to"
    activityDef ||--o{ progRole : "related to"
    activityDef ||--o{ tracker : "related to"
    activityDef ||--o{ tracker01 : "related to"
    activityDef ||--o{ tracker02 : "related to"
    activityDef ||--o{ tracker03 : "related to"
    activityDef ||--o{ tracker04 : "related to"
    activityDef ||--o{ tracker05 : "related to"
