erDiagram
    farUser {
        string id
        string name
    }
    activityDef {
        string id
        string name
    }
    center {
        string id
        string name
    }
    dmProfile {
        string id
        string name
    }
    farGroup {
        string id
        string name
    }
    farPermission {
        string id
        string name
    }
    farRole {
        string id
        string name
    }
    intake {
        string id
        string name
    }
    media {
        string id
        string name
    }
    memberGroup {
        string id
        string name
    }
    partner {
        string id
        string name
    }
    programme {
        string id
        string name
    }
    progRole {
        string id
        string name
    }
    referer {
        string id
        string name
    }

    %% Relationships
    farUser ||--o{ activityDef : "related to"
    farUser ||--o{ center : "related to"
    farUser ||--o{ dmProfile : "related to"
    farUser ||--o{ farGroup : "related to"
    farUser ||--o{ farPermission : "related to"
    farUser ||--o{ farRole : "related to"
    farUser ||--o{ intake : "related to"
    farUser ||--o{ media : "related to"
    farUser ||--o{ memberGroup : "related to"
    farUser ||--o{ partner : "related to"
    farUser ||--o{ programme : "related to"
    farUser ||--o{ progRole : "related to"
    farUser ||--o{ referer : "related to"
