erDiagram
    partner {
        string id
        string name
    }
    activityDef {
        string id
        string name
    }
    center {
        string id
        string name
    }
    dmProfile {
        string id
        string name
    }
    farGroup {
        string id
        string name
    }
    farPermission {
        string id
        string name
    }
    farRole {
        string id
        string name
    }
    farUser {
        string id
        string name
    }
    intake {
        string id
        string name
    }
    media {
        string id
        string name
    }
    memberGroup {
        string id
        string name
    }
    programme {
        string id
        string name
    }
    progRole {
        string id
        string name
    }
    referer {
        string id
        string name
    }

    %% Relationships
    partner ||--o{ activityDef : "related to"
    partner ||--o{ center : "related to"
    partner ||--o{ dmProfile : "related to"
    partner ||--o{ farGroup : "related to"
    partner ||--o{ farPermission : "related to"
    partner ||--o{ farRole : "related to"
    partner ||--o{ farUser : "related to"
    partner ||--o{ intake : "related to"
    partner ||--o{ media : "related to"
    partner ||--o{ memberGroup : "related to"
    partner ||--o{ programme : "related to"
    partner ||--o{ progRole : "related to"
    partner ||--o{ referer : "related to"
