erDiagram
    "pathway_activityDef" {
        UUID ObjectID
        string name
    }

    "pathway_center" {
        UUID ObjectID
        string name
    }

    "pathway_intake" {
        UUID ObjectID
        string name
    }

    "pathway_media" {
        UUID ObjectID
        string name
    }

    "pathway_memberGroup" {
        UUID ObjectID
        string name
    }

    "pathway_partner" {
        UUID ObjectID
        string name
    }

    "pathway_programme" {
        UUID ObjectID
        string name
    }

    "pathway_progRole" {
        UUID ObjectID
        string name
    }

    "pathway_referer" {
        UUID ObjectID
        string name
    }

    "zfarcrycore_dmProfile" {
        UUID ObjectID
        string name
    }

    "zfarcrycore_farGroup" {
        UUID ObjectID
        string name
    }

    "zfarcrycore_farPermission" {
        UUID ObjectID
        string name
    }

    "zfarcrycore_farRole" {
        UUID ObjectID
        string name
    }

    "zfarcrycore_farUser" {
        UUID ObjectID
        string name
    }

    %% Direct FK Relationships
    "pathway_activityDef" ||--|| "pathway_programme" : programmeID
    "pathway_activityDef" ||--|| "pathway_progRole" : role
    "pathway_activityDef" ||--|| "pathway_media" : defaultMediaID
    "pathway_center" ||--|| "zfarcrycore_dmProfile" : dmProfileID
    "pathway_center" ||--|| "pathway_partner" : partnerID
    "pathway_center" ||--|| "pathway_memberGroup" : memberGroupID
    "pathway_intake" ||--|| "pathway_memberGroup" : memberGroupID
    "pathway_intake" ||--|| "pathway_center" : centerID
    "pathway_media" ||--|| "pathway_partner" : partnerID
    "pathway_media" ||--|| "pathway_programme" : programmeID
    "pathway_media" ||--|| "pathway_progRole" : roleID
    "pathway_memberGroup" ||--|| "pathway_partner" : partnerID
    "pathway_partner" ||--|| "zfarcrycore_dmProfile" : dmProfileID
    "pathway_partner" ||--|| "zfarcrycore_dmProfile" : seniorSupportID
    "pathway_programme" ||--|| "pathway_partner" : partnerID
    "pathway_programme" ||--|| "pathway_activityDef" : firstActivityDefID
    "pathway_programme" ||--|| "pathway_activityDef" : lastActivityDefID
    "pathway_progRole" ||--|| "pathway_programme" : programmeID
    "pathway_referer" ||--|| "zfarcrycore_dmProfile" : dmProfileID
    "pathway_referer" ||--|| "pathway_partner" : partnerID
    "pathway_referer" ||--|| "pathway_memberGroup" : memberGroupID
    "pathway_referer" ||--|| "pathway_center" : centerID
    "zfarcrycore_dmProfile" ||--|| "pathway_memberGroup" : memberGroupID
    "zfarcrycore_dmProfile" ||--|| "zfarcrycore_farGroup" : lGroups
    "zfarcrycore_farPermission" ||--|| "zfarcrycore_farRole" : aRoles
    "zfarcrycore_farUser" ||--|| "zfarcrycore_farGroup" : lGroups
    %% End Direct FK Relationships

    %% Special Joins
    "zfarcrycore_farUser" ||--|| "zfarcrycore_dmProfile" : userID_to_userName_userDirectory
    %% End Special Joins

    %% Self-Referencing Relationships for activityDef
    "pathway_activityDef" ||--|| "pathway_activityDef" : onEndID
    "pathway_activityDef" }o--|| "pathway_activityDef" : aCuePointActivities
    "pathway_activityDef" }o--|| "pathway_activityDef" : aInteract1Activities
    "pathway_activityDef" }o--|| "pathway_activityDef" : aInteract2Activities
    "pathway_activityDef" }o--|| "pathway_activityDef" : aInteract3Activities
    "pathway_activityDef" }o--|| "pathway_activityDef" : aInteract4Activities
    "pathway_activityDef" }o--|| "pathway_activityDef" : aInteract5Activities
    %% End Self-Referencing Relationships for activityDef

    %% Self-Referencing Relationships for farPermission
    "zfarcrycore_farPermission" }o--|| "zfarcrycore_farPermission" : aRelatedtypes
    %% End Self-Referencing Relationships for farPermission

    %% Join Table Relationships
    "pathway_activityDef" }o--|| "pathway_media" : aMediaIDs
    "pathway_center" }o--|| "zfarcrycore_dmProfile" : aUsers
    "pathway_center" }o--|| "pathway_referer" : aReferers
    "pathway_memberGroup" }o--|| "zfarcrycore_farUser" : aFarcryUsers
    "pathway_partner" }o--|| "pathway_center" : aCenters
    "pathway_partner" }o--|| "pathway_referer" : aReferers
    "pathway_programme" }o--|| "pathway_activityDef" : aFollowupActivityDefIDs
    "zfarcrycore_dmProfile" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farGroup" : aGroups
    "zfarcrycore_farRole" }o--|| "zfarcrycore_farPermission" : aPermissions
    "zfarcrycore_farUser" }o--|| "zfarcrycore_farGroup" : aGroups
    %% End Join Table Relationships


    %% Entity Styling
    style pathway_activityDef fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_center fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_intake fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_media fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_memberGroup fill:#2196f3,stroke:#1976d2,stroke-width:1px,color:#fff
    style pathway_partner fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_programme fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_progRole fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style pathway_referer fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style zfarcrycore_dmProfile fill:#2196f3,stroke:#1976d2,stroke-width:1px,color:#fff
    style zfarcrycore_farGroup fill:#2196f3,stroke:#1976d2,stroke-width:1px,color:#fff
    style zfarcrycore_farPermission fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style zfarcrycore_farRole fill:#9e9e9e,stroke:#fff,stroke-width:1px,color:#fff
    style zfarcrycore_farUser fill:#ff9800,stroke:#e65100,stroke-width:2px,color:#fff

