erDiagram
  activity {
    objectID UUID
  }
  activityDef {
    objectID UUID
  }
  address {
    objectID UUID
  }
  apiAccessKey {
    objectID UUID
  }
  center {
    objectID UUID
  }
  configAPI {
    objectID UUID
  }
  device {
    objectID UUID
  }
  dmFacts {
    objectID UUID
  }
  dmFile {
    objectID UUID
  }
  dmHTML {
    objectID UUID
  }
  dmImage {
    objectID UUID
  }
  dmNavigation {
    objectID UUID
  }
  dmProfile {
    objectID UUID
  }
  farGroup {
    objectID UUID
  }
  farPermission {
    objectID UUID
  }
  farRole {
    objectID UUID
  }
  farUser {
    objectID UUID
  }
  freeagent {
    objectID UUID
  }
  guide {
    objectID UUID
  }
  intake {
    objectID UUID
  }
  journal {
    objectID UUID
  }
  journalDef {
    objectID UUID
  }
  JWTapp {
    objectID UUID
  }
  library {
    objectID UUID
  }
  media {
    objectID UUID
  }
  member {
    objectID UUID
  }
  memberGroup {
    objectID UUID
  }
  memberType {
    objectID UUID
  }
  oAuth2service {
    objectID UUID
  }
  partner {
    objectID UUID
  }
  progMember {
    objectID UUID
  }
  programme {
    objectID UUID
  }
  progRole {
    objectID UUID
  }
  promotion {
    objectID UUID
  }
  referer {
    objectID UUID
  }
  report {
    objectID UUID
  }
  slack {
    objectID UUID
  }
  soundcloud {
    objectID UUID
  }
  SSQ_arthritis01 {
    objectID UUID
  }
  SSQ_pain01 {
    objectID UUID
  }
  SSQ_stress01 {
    objectID UUID
  }
  swagger {
    objectID UUID
  }
  token {
    objectID UUID
  }
  tracker {
    objectID UUID
  }
  trackerDef {
    objectID UUID
  }
  SSQ_stress01 ||--o{ member : fk
  partner ||--o{ dmProfile : fk
  library ||--o{ activity : fk
  intake ||--o{ center : fk
  journal ||--o{ journalDef : fk
  member ||--o{ address : fk
  media ||--o{ partner : fk
  progRole ||--o{ programme : fk
  report ||--o{ member : fk
  activityDef ||--o{ journalDef : fk
  address ||--o{ member : fk
  activity ||--o{ progMember : fk
  guide ||--o{ partner : fk
  partner ||--o{ center : fk
  media ||--o{ progRole : fk
  activityDef ||--o{ activityDef : fk
  library ||--o{ progMember : fk
  SSQ_pain01 ||--o{ programme : fk
  activity ||--o{ activityDef : fk
  activityDef ||--o{ guide : fk
  member ||--o{ activityDef : fk
  member ||--o{ progRole : fk
  report ||--o{ memberGroup : fk
  center ||--o{ dmImage : fk
  guide ||--o{ dmImage : fk
  report ||--o{ memberType : fk
  memberGroup ||--o{ dmNavigation : fk
  activityDef ||--o{ media : fk
  progMember ||--o{ activity : fk
  referer ||--o{ partner : fk
  programme ||--o{ partner : fk
  guide ||--o{ center : fk
  journal ||--o{ activity : fk
  memberGroup ||--o{ dmFile : fk
  SSQ_pain01 ||--o{ member : fk
  report ||--o{ programme : fk
  memberGroup ||--o{ dmHTML : fk
  SSQ_pain01 ||--o{ progMember : fk
  member ||--o{ memberGroup : fk
  memberGroup ||--o{ farUser : fk
  referer ||--o{ memberGroup : fk
  activityDef ||--o{ dmImage : fk
  promotion ||--o{ partner : fk
  library ||--o{ media : fk
  center ||--o{ referer : fk
  center ||--o{ partner : fk
  member ||--o{ partner : fk
  activityDef ||--o{ trackerDef : fk
  programme ||--o{ trackerDef : fk
  SSQ_arthritis01 ||--o{ programme : fk
  partner ||--o{ referer : fk
  activityDef ||--o{ progRole : fk
  trackerDef ||--o{ programme : fk
  referer ||--o{ dmImage : fk
  SSQ_arthritis01 ||--o{ progMember : fk
  partner ||--o{ dmImage : fk
  promotion ||--o{ programme : fk
  memberGroup ||--o{ partner : fk
  programme ||--o{ activityDef : fk
  progMember ||--o{ member : fk
  intake ||--o{ memberGroup : fk
  SSQ_arthritis01 ||--o{ member : fk
  tracker ||--o{ trackerDef : fk
  SSQ_stress01 ||--o{ progMember : fk
  center ||--o{ dmProfile : fk
  programme ||--o{ dmImage : fk
  oAuth2service ||--o{ JWTapp : fk
  media ||--o{ programme : fk
  tracker ||--o{ progMember : fk
  member ||--o{ center : fk
  SSQ_stress01 ||--o{ programme : fk
  programme ||--o{ dmFile : fk
  memberGroup ||--o{ dmImage : fk
  intake ||--o{ member : fk
  referer ||--o{ center : fk
  dmNavigation ||--o{ dmImage : fk
  center ||--o{ memberGroup : fk
  address ||--o{ dmProfile : fk
  journalDef ||--o{ programme : fk
  report ||--o{ partner : fk
  tracker ||--o{ activity : fk
  media ||--o{ guide : fk
  progMember ||--o{ programme : fk
  activityDef ||--o{ programme : fk
  member ||--o{ memberType : fk
  member ||--o{ referer : fk
  journal ||--o{ progMember : fk
  journalDef ||--o{ trackerDef : fk
  referer ||--o{ dmProfile : fk
  farUser ||--|| dmProfile : userid_to_userName
  farUser ||--o{ farGroup : aGroups
  farRole ||--o{ farGroup : aGroups
  farRole ||--o{ farPermission : aPermissions
